--create table

CREATE TABLE "AVWRPT"."DAILY_CRON_JOB"
 (	"JOBID" VARCHAR2(30 BYTE) primary key,
"JOBNAME" VARCHAR2(30 BYTE) not null,
"JOBGROUP" VARCHAR2(30 BYTE) not null,
"JOBSTATUS" VARCHAR2(10 BYTE),
"CRON"  VARCHAR2(20 BYTE) not null,
"JOBDEC" VARCHAR2(2000 BYTE),
"POOL" VARCHAR2(8 BYTE)
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

--create public synonym
CREATE PUBLIC SYNONYM DAILY_CRON_JOB FOR AVWRPT.DAILY_CRON_JOB;

--grant privilege

GRANT ALL ON "DAILY_CRON_JOB" TO "tantan";


CREATE sequence SEQ_JOB_ID minvalue 1 maxvalue 99999999 start with 1 increment BY 1 nocache ORDER;


CREATE OR REPLACE TRIGGER tri_DAILY_CRON_JOB_id before
  INSERT ON DAILY_CRON_JOB
    FOR EACH row DECLARE nextid NUMBER;
  BEGIN
    IF :new.JOBID
    IS
      NULL or :new.JOBID=0 THEN
      SELECT SEQ_JOB_ID.nextval
      INTO nextid FROM sys.dual;
      :new.JOBID:=nextid;
    END IF;
  END tri_DAILY_CRON_JOB_id;


CREATE UNIQUE INDEX "DAILY_CRON_JOB_U1" ON "AVWRPT"."DAILY_CRON_JOB" ("JOBGROUP", "JOBNAME")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
